### PR TITLE
[Outlook] (spam reporting) Separate event-handling JavaScript files

### LINKED ISSUE #798: The Spam Reporting example uses Office.onReady, which will not work on Classic Outlook
**URL of sample**

https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-spam-reporting

**Describe the bug**

This sample wraps the `Office.actions.associate(...)` call, which is only needed on classic Outlook for windows, in an `Office.onReady(...)` call. That `onReady` call will never be invoked on classic Outlook for this style of add-in, per MS's documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/spam-reporting

> As you develop a spam-reporting add-in that will run in Outlook on Windows, keep the following in mind.
> * Imports aren't currently supported in the JavaScript file that contains the code to handle the spam-reporting event.
> * Code included in the `Office.onReady()` and `Office.initialize` functions won't run. You must add any add-in startup logic, such as checking the user's Outlook version, to your event handlers instead.

**To Reproduce**

1. Install the sample, and try to use it to report a message on classic Outlook for Windows.
2. The add-in gets stuck showing "Pending..." after you try to submit your report.

**Expected behavior**

The report doesn't get stuck, and runs to completion correctly.

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
- Host [Excel, Word, PowerPoint, etc.]: Outlook
- Office version number: latest
- Operating System: Windows 11
- Browser (if using Office Online): N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by samantharamon**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                               |
| New feature?    | no                             |
| New sample?     | no                            |
| Related issues? | Fixes #798 |

## What's in this Pull Request?

Creates a separate event-handling JavaScript file for classic Outlook on Windows.

### CODE REVIEW

File: Samples/outlook-spam-reporting/src/spamreporting_classic.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    }
+  );
+}
+
+/**
+ * IMPORTANT: To ensure your add-in is supported in the classic Outlook client on Windows,
+ * remember to map the event handler name specified in the manifest to its JavaScript counterpart.
+ */
+if (Office.context.platform === Office.PlatformType.PC || Office.context.platform == null) {
+  Office.actions.associate("onSpamReport", onSpamReport); }
```
Comment (ElizabethSamuel-MSFT) [inline Samples/outlook-spam-reporting/src/spamreporting_classic.js:51]:
```suggestion
  Office.actions.associate("onSpamReport", onSpamReport);
}
```

**Review by ElizabethSamuel-MSFT — APPROVED** [review]
